apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: magnews-restcontroller-service
  namespace: default
  labels:
    app: magnews-restcontroller-service
spec:
  template:
    spec:
      containers:
      - image: docker.io/lucacelardo/magnewsrestcontroller:1.0.0