apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: magnews-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster-kafka-0
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824